// Targeted by JavaCPP version 1.3.3: DO NOT EDIT THIS FILE

package com.example.lettuce;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class NativeLibrary extends com.example.lettuce.config.NativeLibraryConfigurer {
    static { Loader.load(); }

// Parsed from NativeLibrary.h

// #include <string>
    @Namespace("NativeLibrary") public static class NativeClass extends Pointer {
        static { Loader.load(); }
        /** Default native constructor. */
        public NativeClass() { super((Pointer)null); allocate(); }
        /** Native array allocator. Access with {@link Pointer#position(long)}. */
        public NativeClass(long size) { super((Pointer)null); allocateArray(size); }
        /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
        public NativeClass(Pointer p) { super(p); }
        private native void allocate();
        private native void allocateArray(long size);
        @Override public NativeClass position(long position) {
            return (NativeClass)super.position(position);
        }
    
            public native @StdString BytePointer get_property();
            public native void set_property(@StdString BytePointer property);
            public native void set_property(@StdString String property);
            public native @StdString BytePointer property(); public native NativeClass property(BytePointer property);
    }



}
